# Azure Pipelines YAML file

trigger:
  - main

variables:
  # Set the Python version to use
  pythonVersion: '3.9'

jobs:

- job: RunDetector
  pool:
    vmImage: 'ubuntu-latest'
    
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Archive the project files into a .zip file for deployment
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true
    displayName: 'Archive files for deployment'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '<YourServiceConnectionName>'  # Replace with your service connection name
      appName: 'your-app-name'                          # Replace with your Azure Web App name
      package: '$(Build.ArtifactStagingDirectory)/app.zip'
    displayName: 'Deploy to Azure Web App'