# Azure Pipelines YAML file

trigger:
  - main

variables:
  # Set the Python version to use
  pythonVersion: '3.9'

jobs:

- job: RunDetector
  pool:
    vmImage: 'ubuntu-latest'
    
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Build and deploy to Azure App Service
    uses: azure/webapps-deploy@v2
    with:
      app-name: 'your-app-name'
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      package: |
        app.py
        models/person_model.pt
        models/ball_model.pt
        deep_sort/deep/checkpoint/ckpt.t7
        detector/__init__.py
        detector/realtime_detector.py
        requirements.txt