# Azure Pipelines YAML file

trigger:
  - main

variables:
  # Set the Python version to use
  pythonVersion: '3.9'

jobs:

- job: RunDetector
  pool:
    vmImage: 'ubuntu-latest'
    
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'YourServiceConnectionName'  # Replace with the name of your service connection in Azure DevOps
      appName: 'your-app-name'  # Replace with your actual app name in Azure
      package: '$(System.DefaultWorkingDirectory)'  # This points to the working directory where artifacts are located
    displayName: 'Deploy to Azure Web App'